/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testhiber;

/**
 *
 * @author augus
 */
public class FormIni extends javax.swing.JFrame {

    /**
     * Creates new form FormIni
     */
    public FormIni() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bFormVer = new javax.swing.JButton();
        bFAgregar = new javax.swing.JButton();
        bFBorrar = new javax.swing.JButton();
        bPartidos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CAMPEONATO");

        bFormVer.setText("Ver Equipos");
        bFormVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFormVerActionPerformed(evt);
            }
        });

        bFAgregar.setText("Agregar");
        bFAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFAgregarActionPerformed(evt);
            }
        });

        bFBorrar.setText("Eliminar");
        bFBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFBorrarActionPerformed(evt);
            }
        });

        bPartidos.setText("Partidos");
        bPartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPartidosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bPartidos)
                    .addComponent(bFBorrar)
                    .addComponent(bFAgregar)
                    .addComponent(bFormVer))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(bFormVer)
                .addGap(33, 33, 33)
                .addComponent(bFAgregar)
                .addGap(32, 32, 32)
                .addComponent(bFBorrar)
                .addGap(33, 33, 33)
                .addComponent(bPartidos)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bFormVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFormVerActionPerformed
        // TODO add your handling code here:
        FormVer f1=new FormVer();
        f1.setVisible(true);
    }//GEN-LAST:event_bFormVerActionPerformed

    private void bFAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFAgregarActionPerformed
        // TODO add your handling code here:
        FAgregar f2=new FAgregar();
        f2.setVisible(true);
    }//GEN-LAST:event_bFAgregarActionPerformed

    private void bFBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFBorrarActionPerformed
        // TODO add your handling code here:
        FBorrar f3=new FBorrar();
        f3.setVisible(true);
    }//GEN-LAST:event_bFBorrarActionPerformed

    private void bPartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPartidosActionPerformed
        // TODO add your handling code here:
        FPartidos f4=new FPartidos();
        f4.setVisible(true);
    }//GEN-LAST:event_bPartidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormIni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormIni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormIni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormIni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormIni().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bFAgregar;
    private javax.swing.JButton bFBorrar;
    private javax.swing.JButton bFormVer;
    private javax.swing.JButton bPartidos;
    // End of variables declaration//GEN-END:variables
}
