package pojos;
// Generated 04/12/2023 01:32:18 by Hibernate Tools 4.3.1



/**
 * Equipos generated by hbm2java
 */
public class Equipos  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Integer titulares;
     private Integer suplentes;
     private String tecnico;
     private Integer puntos;
     private Integer partidos;

    public Equipos() {
    }

    public Equipos(String nombre, Integer titulares, Integer suplentes, String tecnico, Integer puntos, Integer partidos) {
       this.nombre = nombre;
       this.titulares = titulares;
       this.suplentes = suplentes;
       this.tecnico = tecnico;
       this.puntos = puntos;
       this.partidos = partidos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getTitulares() {
        return this.titulares;
    }
    
    public void setTitulares(Integer titulares) {
        this.titulares = titulares;
    }
    public Integer getSuplentes() {
        return this.suplentes;
    }
    
    public void setSuplentes(Integer suplentes) {
        this.suplentes = suplentes;
    }
    public String getTecnico() {
        return this.tecnico;
    }
    
    public void setTecnico(String tecnico) {
        this.tecnico = tecnico;
    }
    public Integer getPuntos() {
        return this.puntos;
    }
    
    public void setPuntos(Integer puntos) {
        this.puntos = puntos;
    }
    public Integer getPartidos() {
        return this.partidos;
    }
    
    public void setPartidos(Integer partidos) {
        this.partidos = partidos;
    }
    
    @Override
    public String toString(){
        return this.nombre;
    }




}


